version: '3.8'

services:
  frontend:
    build:
      context: ./frontend1  # Path to the frontend directory containing the Dockerfile
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Map local port 3000 to the container's port 80
    networks:
      - app-network

  backend:
    build:
      context: ./backend  # Path to the backend directory containing the Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Map local port 8000 to the container's port 8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
